CREATE DATABASE Olimpia;

USE Olimpia;


CREATE TABLE O_ORSZAGOK(AZON INT,
	                    ORSZAG VARCHAR(50),
	                    TERULET INT,
	                    LAKOSSAG INT,
	                    FOVAROS VARCHAR(40),
                        FOLDRESZ VARCHAR(50),
	 CONSTRAINT O_ORSZ_PK PRIMARY KEY (AZON),
     CONSTRAINT O_ORSZ_UK_ORSZ UNIQUE (ORSZAG));
  
CREATE TABLE O_EREM_TABLA(ORSZAG_AZON INT,
	                      ARANY INT,
	                      EZUST INT,
	                      BRONZ INT,
	 CONSTRAINT O_ET_PK PRIMARY KEY (ORSZAG_AZON),
  	 CONSTRAINT O_ET_FK FOREIGN KEY (ORSZAG_AZON) REFERENCES O_ORSZAGOK (AZON));
 
CREATE TABLE O_VERSENYZOK(AZON INT,
                          NEV VARCHAR(50),
                          SZUL_DAT DATE,
                          ORSZAG_AZON INT,
                          EGYEN_CSAPAT VARCHAR(1),
                          SZUL_HELY VARCHAR(50),
    CONSTRAINT O_VERS_PK PRIMARY KEY(AZON),
    CONSTRAINT O_VNY_UK UNIQUE (NEV,ORSZAG_AZON,SZUL_DAT),
    CONSTRAINT O_VERS_FK_ORSZ FOREIGN KEY (ORSZAG_AZON) REFERENCES O_ORSZAGOK (AZON) );
          
CREATE TABLE O_CSAPATTAGOK(VERSENYZO_AZON INT,
	                       CSAPAT_AZON INT,
    CONSTRAINT O_CST_PK PRIMARY KEY (VERSENYZO_AZON, CSAPAT_AZON),
    CONSTRAINT O_CST_FK_CS FOREIGN KEY (CSAPAT_AZON) REFERENCES O_VERSENYZOK (AZON),
    CONSTRAINT O_CST_FK_T FOREIGN KEY (VERSENYZO_AZON) REFERENCES O_VERSENYZOK (AZON));
          
CREATE TABLE O_SPORTAGAK(AZON INT,
	                     NEV VARCHAR(50),
    CONSTRAINT O_SPAG_PK PRIMARY KEY (AZON),
    CONSTRAINT O_SPAG_UK UNIQUE (NEV));
        
CREATE TABLE O_VERSENYSZAMOK (AZON INT,
	                          SPORTAG_AZON INT,
	                          VERSENYSZAM VARCHAR(50),
	                          FERFI_NOI VARCHAR(5),
    CONSTRAINT O_VSZAM_PK PRIMARY KEY (AZON),
    CONSTRAINT O_VSZAM_UK UNIQUE (SPORTAG_AZON, VERSENYSZAM, FERFI_NOI),
    CONSTRAINT O_VSZAM_FK_SP FOREIGN KEY (SPORTAG_AZON) REFERENCES O_SPORTAGAK (AZON));

CREATE TABLE O_EREDMENYEK (VERSENYZO_AZON INT,
                           VERSENYSZAM_AZON INT,
                           HELYEZES INT,
                           MEGJEGYZES VARCHAR(150),
    CONSTRAINT O_E_PK PRIMARY KEY  (VERSENYZO_AZON, VERSENYSZAM_AZON),
    CONSTRAINT O_E_FK_VSZ FOREIGN KEY ( VERSENYSZAM_AZON) REFERENCES O_VERSENYSZAMOK (AZON),
    CONSTRAINT O_E_FK_VNY FOREIGN KEY (VERSENYZO_AZON) REFERENCES O_VERSENYZOK (AZON) );