USE Olimpia;

INSERT INTO o_sportagak (AZON,NEV) VALUES (301,'Asztalitenisz');                                                                           
INSERT INTO o_sportagak (AZON,NEV) VALUES (302,'Labdarúgás');                                                                              
INSERT INTO o_sportagak (AZON,NEV) VALUES (303,'Szinkronúszás');                                                                           
INSERT INTO o_sportagak (AZON,NEV) VALUES (304,'Atlétika');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (305,'Lovaglás');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (306,'Tékvandó');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (307,'Baseball');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (308,'Lövészet');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (309,'Tenisz');                                                                                  
INSERT INTO o_sportagak (AZON,NEV) VALUES (310,'Birkózás');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (311,'Műugrás');                                                                                 
INSERT INTO o_sportagak (AZON,NEV) VALUES (312,'Tollaslabda');                                                                             
INSERT INTO o_sportagak (AZON,NEV) VALUES (313,'Cselgáncs');                                                                               
INSERT INTO o_sportagak (AZON,NEV) VALUES (314,'Országúti kerékpár');                                                                      
INSERT INTO o_sportagak (AZON,NEV) VALUES (315,'Torna');                                                                                   
INSERT INTO o_sportagak (AZON,NEV) VALUES (316,'Evezés');                                                                                  
INSERT INTO o_sportagak (AZON,NEV) VALUES (317,'Ökölvívás');                                                                               
INSERT INTO o_sportagak (AZON,NEV) VALUES (318,'Trampolin');                                                                               
INSERT INTO o_sportagak (AZON,NEV) VALUES (319,'Gyeplabda');                                                                               
INSERT INTO o_sportagak (AZON,NEV) VALUES (320,'Öttusa');                                                                                  
INSERT INTO o_sportagak (AZON,NEV) VALUES (321,'Triatlon');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (322,'Hegyi kerékpár');                                                                          
INSERT INTO o_sportagak (AZON,NEV) VALUES (323,'Pályakerékpár');                                                                           
INSERT INTO o_sportagak (AZON,NEV) VALUES (324,'Úszás');                                                                                   
INSERT INTO o_sportagak (AZON,NEV) VALUES (325,'Íjászat');                                                                                 
INSERT INTO o_sportagak (AZON,NEV) VALUES (326,'Ritmikus sportgimnasztika');                                                               
INSERT INTO o_sportagak (AZON,NEV) VALUES (327,'Vitorlázás');                                                                              
INSERT INTO o_sportagak (AZON,NEV) VALUES (328,'Kajak-kenu');                                                                              
INSERT INTO o_sportagak (AZON,NEV) VALUES (329,'Röplabda');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (330,'Vívás');                                                                                   
INSERT INTO o_sportagak (AZON,NEV) VALUES (331,'Kajak-szlalom');                                                                           
INSERT INTO o_sportagak (AZON,NEV) VALUES (332,'Softball');                                                                                
INSERT INTO o_sportagak (AZON,NEV) VALUES (333,'Vízilabda');                                                                               
INSERT INTO o_sportagak (AZON,NEV) VALUES (334,'Kézilabda');                                                                               
INSERT INTO o_sportagak (AZON,NEV) VALUES (335,'Strandröplabda');                                                                          
INSERT INTO o_sportagak (AZON,NEV) VALUES (336,'Kosárlabda');                                                                              
INSERT INTO o_sportagak (AZON,NEV) VALUES (337,'Súlyemelés'); 